import { GridBox, ComboBox } from "std-widgets.slint";
import { ComboBoxScroll } from "../components/ComboBoxScroll.slint";

export component HotkeysTab inherits VerticalLayout {
    in property <[string]> actions;
    in-out property <int> box1_1_current_index <=> box1_1.current-index;
    in-out property <int> box1_2_current_index <=> box1_2.current-index;
    in-out property <int> box1_3_current_index <=> box1_3.current-index;
    in-out property <int> box2_1_current_index <=> box2_1.current-index;
    in-out property <int> box2_2_current_index <=> box2_2.current-index;
    in-out property <int> box2_3_current_index <=> box2_3.current-index;
    in-out property <int> box3_1_current_index <=> box3_1.current-index;
    in-out property <int> box3_2_current_index <=> box3_2.current-index;
    in-out property <int> box3_3_current_index <=> box3_3.current-index;

    padding-left: 15px;
    padding-top: 15px;

    // Button 1
    Text {
        font-size: 17px;
        text: "Button 1 click action:";
        height: 24px;
    }
    GridBox {
        Row {
            box1_1 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
            box1_2 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
            box1_3 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
        }
    }
    // Button 2
    Text {
        font-size: 17px;
        text: "Button 2 click action:";
        height: 24px;
    }
    GridBox {
        Row {
            box2_1 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
            box2_2 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
            box2_3 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
        }
    }
    // Button 3
    Text {
        font-size: 17px;
        text: "Button 3 click action:";
        height: 24px;
    }
    GridBox {
        Row {
            box3_1 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
            box3_2 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
            box3_3 := ComboBoxScroll {
                height: 40px;
                model: actions;
            }
        }
    }
}